"""add_english_fields_to_announcements

Revision ID: dde4ca300a7f
Revises: 503107688e81
Create Date: 2025-11-27 17:59:40.392319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde4ca300a7f'
down_revision: Union[str, Sequence[str], None] = '503107688e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('title_en', sa.String(length=200), nullable=True))
    op.add_column('announcements', sa.Column('content_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'content_en')
    op.drop_column('announcements', 'title_en')
    # ### end Alembic commands ###
