"""add_english_fields_to_items

Revision ID: f6a77ec0407d
Revises: dde4ca300a7f
Create Date: 2025-11-27 18:03:51.306103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a77ec0407d'
down_revision: Union[str, Sequence[str], None] = 'dde4ca300a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_items', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('inspection_items', sa.Column('description_en', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_items', 'description_en')
    op.drop_column('inspection_items', 'name_en')
    # ### end Alembic commands ###
